### PR TITLE
Print Hypre preconditioner setup error

### LINKED ISSUE #2672: Bad linear solver performance when switching oil and water order in SPE10
1. Take https://github.com/GEOS-DEV/MAELSTROM/tree/master/usecases/francois/SPE10/flow
2. Switch order { oil, water } -> { water, oil }
3. Run and observe:
```
Time: 0.00e+00 s, dt: 10000 s, Cycle: 0
    Attempt:  0, ConfigurationIter:  0, NewtonIter:  0
    ( Rflow ) = ( 2.37e+03 ) ;     ( R ) = ( 2.37e+03 ) ; 
{ 3 }
		Linear Solver | NotConverged | Iterations: 200 | Final Rel Res: 0.167039 | Make Restrictor Time: 0 | Compute Auu Time: 0 | SC Filter Time: 0 | Setup Time: 0.600905 s | Solve Time: 33.2732 s
    Attempt:  0, ConfigurationIter:  0, NewtonIter:  1
    ( Rflow ) = ( 2.34e+03 ) ;     ( R ) = ( 2.34e+03 ) ; 
    Last LinSolve(iter,res) = ( 200, 1.67e-01 ) ; 
{ 3 }
		Linear Solver | NotConverged | Iterations: 200 | Final Rel Res: 0.151071 | Make Restrictor Time: 0 | Compute Auu Time: 0 | SC Filter Time: 0 | Setup Time: 0.59512 s | Solve Time: 32.0907 s
    Attempt:  0, ConfigurationIter:  0, NewtonIter:  2
    ( Rflow ) = ( 2.32e+03 ) ;     ( R ) = ( 2.32e+03 ) ; 
    Last LinSolve(iter,res) = ( 200, 1.51e-01 ) ; 
{ 3 }
		Linear Solver | NotConverged | Iterations: 200 | Final Rel Res: 0.149277 | Make Restrictor Time: 0 | Compute Auu Time: 0 | SC Filter Time: 0 | Setup Time: 0.550563 s | Solve Time: 31.2461 s
    Attempt:  0, ConfigurationIter:  0, NewtonIter:  3
    ( Rflow ) = ( 2.30e+03 ) ;     ( R ) = ( 2.30e+03 ) ; 
    Last LinSolve(iter,res) = ( 200, 1.49e-01 ) ; 
{ 3 }
		Linear Solver | NotConverged | Iterations: 200 | Final Rel Res: 0.112426 | Make Restrictor Time: 0 | Compute Auu Time: 0 | SC Filter Time: 0 | Setup Time: 0.534897 s | Solve Time: 33.8116 s
    Attempt:  0, ConfigurationIter:  0, NewtonIter:  4
    ( Rflow ) = ( 2.28e+03 ) ;     ( R ) = ( 2.28e+03 ) ; 
    Last LinSolve(iter,res) = ( 200, 1.12e-01 ) ; 
{ 3 }
		Linear Solver | NotConverged | Iterations: 200 | Final Rel Res: 0.0946187 | Make Restrictor Time: 0 | Compute Auu Time: 0 | SC Filter Time: 0 | Setup Time: 0.732886 s | Solve Time: 45.3103 s
    Attempt:  0, ConfigurationIter:  0, NewtonIter:  5
    ( Rflow ) = ( 2.25e+03 ) ;     ( R ) = ( 2.25e+03 ) ; 
    Last LinSolve(iter,res) = ( 200, 9.46e-02 ) ; 
```
4. Set initial water to pure zero like that:
```
    <FieldSpecification
      name="initialComposition_oil"
      initialCondition="1"
      setNames="{ all }"
      objectPath="ElementRegions/region/block"
      fieldName="globalCompFraction"
      component="0"
      scale="1.0"/>
    <FieldSpecification
      name="initialComposition_water"
      initialCondition="1"
      setNames="{ all }"
      objectPath="ElementRegions/region/block"
      fieldName="globalCompFraction"
      component="1"
      scale="0.0"/>
```
Observe crash:
```
Time: 0.00e+00 s, dt: 10000 s, Cycle: 0
    Attempt:  0, ConfigurationIter:  0, NewtonIter:  0
    ( Rflow ) = ( 2.37e+03 ) ;     ( R ) = ( 2.37e+03 ) ; 
{ 3 }
Received signal 8: Floating point exception
Floating point exception:

** StackTrace of 14 frames **
Frame 0: /lib64/libc.so.6 
Frame 1: hypre_FlexGMRESSolve 
Frame 2: geos::HypreSolver::doSolve(geos::HypreVector const&, geos::HypreVector&) const 
Frame 3: geos::HypreSolver::solve(geos::HypreVector const&, geos::HypreVector&) const 
Frame 4: geos::SolverBase::solveLinearSystem(geos::DofManager const&, geos::HypreMatrix&, geos::HypreVector&, geos::HypreVector&) 
Frame 5: geos::SolverBase::solveNonlinearSystem(double const&, double const&, int, geos::DomainPartition&) 
Frame 6: geos::SolverBase::nonlinearImplicitStep(double const&, double const&, int, geos::DomainPartition&) 
Frame 7: geos::SolverBase::solverStep(double const&, double const&, int, geos::DomainPartition&) 
Frame 8: geos::SolverBase::execute(double, double, int, int, double, geos::DomainPartition&) 
Frame 9: geos::EventBase::execute(double, double, int, int, double, geos::DomainPartition&) 
Frame 10: geos::EventManager::run(geos::DomainPartition&) 
Frame 11: geos::GeosxState::run() 
Frame 12: main 
Frame 13: __libc_start_main 
Frame 14: /data/rpo_ptls/GEOSX/residual_flash/x86_64/RHEL7/GEOS/0.2.0--pt_residual-flash/install-CPU-OPTO2-Hypre-GCC_10.2.0-ompi_hpcx-OMP-relwithdebinfo/bin/geos 
=====
```

### PR DESCRIPTION
**Pull request by paveltomin**
need to go after https://github.com/GEOS-DEV/GEOS/pull/2928

### CODE REVIEW

File: src/coreComponents/linearAlgebra/interfaces/hypre/HyprePreconditioner.cpp [hunk 1]
```diff
@@ -392,7 +392,12 @@ void HyprePreconditioner::setup( Matrix const & mat )
     // Perform setup of the main solver, if needed
     if( m_precond->setup )
     {
-      GEOS_LAI_CHECK_ERROR( m_precond->setup( m_precond->ptr, precondMat.unwrapped(), nullptr, nullptr ) );
+      auto const ierr = m_precond->setup( m_precond->ptr, precondMat.unwrapped(), nullptr, nullptr );
```
Comment (castelletto1) [inline src/coreComponents/linearAlgebra/interfaces/hypre/HyprePreconditioner.cpp]:
```suggestion
      HYPRE_Int const ierr = m_precond->setup( m_precond->ptr, precondMat.unwrapped(), nullptr, nullptr );
```

**Review by castelletto1 — APPROVED** [review]

**Review by victorapm — APPROVED** [review]
Looks great!
