### PR TITLE
HDF5 Collective Operations Flags

### LINKED ISSUE #2716: HDF5 errors when running with MPI
Running this case https://geosx-geosx.readthedocs-hosted.com/en/latest/docs/sphinx/basicExamples/multiphaseFlowWithWells/Example.html

Serial runs just fine, when run with mpirun:
`OMP_NUM_THREADS=1 mpirun -n 2 geosx -i deadOilEgg_benchmark.xml`
HDF5 complains at the end of simulation when timeHistoryOutput is triggered:
```
Cleaning up events
HDF5-DIAG: Error detected in HDF5 (1.12.1) MPI-process 0:
  #000: ../../hdf5/src/H5D.c line 285 in H5Dopen2(): unable to open dataset
    major: Dataset
    minor: Can't open object
  #001: ../../hdf5/src/H5VLcallback.c line 1910 in H5VL_dataset_open(): dataset open failed
    major: Virtual Object Layer
    minor: Can't open object
  #002: ../../hdf5/src/H5VLcallback.c line 1877 in H5VL__dataset_open(): dataset open failed
    major: Virtual Object Layer
    minor: Can't open object
  #003: ../../hdf5/src/H5VLnative_dataset.c line 123 in H5VL__native_dataset_open(): unable to open dataset
    major: Dataset
    minor: Can't open object
  #004: ../../hdf5/src/H5Dint.c line 1483 in H5D__open_name(): not found
    major: Dataset
    minor: Object not found
  #005: ../../hdf5/src/H5Gloc.c line 442 in H5G_loc_find(): can't find object
    major: Symbol table
    minor: Object not found
  #006: ../../hdf5/src/H5Gtraverse.c line 837 in H5G_traverse(): internal path traversal failed
    major: Symbol table
    minor: Object not found
  #007: ../../hdf5/src/H5Gtraverse.c line 613 in H5G__traverse_real(): traversal operator failed
    major: Symbol table
    minor: Callback failed
  #008: ../../hdf5/src/H5Gloc.c line 399 in H5G__loc_find_cb(): object 'wellElementMixtureConnectionRate Time' doesn't exist
    major: Symbol table
    minor: Object not found
```
Output files contain duplicates:
image

### PR DESCRIPTION
**Pull request by wrtobin**
resolves #2716

### CODE REVIEW

**Comment by rrsettgast** [comment]
@drmichaeltcvx @paveltomin @untereiner 
Does this fix your issues?

**Comment by paveltomin** [comment]
> @drmichaeltcvx @paveltomin @untereiner Does this fix your issues?

nope https://github.com/GEOS-DEV/GEOS/issues/2716#issuecomment-2179036420

**Review by paveltomin — APPROVED** [review]

**Comment by paveltomin** [comment]
my issue got resolved, thanks

File: src/coreComponents/fileIO/Outputs/TimeHistoryOutput.cpp [hunk 1]
```diff
@@ -84,12 +87,13 @@ void TimeHistoryOutput::initCollectorParallel( DomainPartition const & domain, H
...
   };
 
-  // FIXME Why stop (pseudo) recursion at one single level?
   registerBufferCalls( collector );
+  MpiWrapper::barrier( MPI_COMM_GEOSX );
 
   for( localIndex metaIdx = 0; metaIdx < collector.numMetaDataCollectors(); ++metaIdx )
   {
     registerBufferCalls( collector.getMetaDataCollector( metaIdx ), collector.getTargetName() + " " );
+    MpiWrapper::barrier( MPI_COMM_GEOSX );
```
Comment (rrsettgast) [inline src/coreComponents/fileIO/Outputs/TimeHistoryOutput.cpp:96]: Are all of these required?

File: src/coreComponents/fileIO/Outputs/TimeHistoryOutput.cpp [hunk 2]
```diff
@@ -31,6 +31,8 @@ TimeHistoryOutput::TimeHistoryOutput( string const & name,
   m_recordCount( 0 ),
   m_io( )
 {
+  enableLogLevelInput();
```
Comment (rrsettgast) [inline src/coreComponents/fileIO/Outputs/TimeHistoryOutput.cpp:34]: is this intended to be committed or was it debugging?

**Review by rrsettgast — APPROVED** [review]
@wrtobin 
My only comment of note is that there are a lot of MPI_Barrier calls that have been added. Are you sure they are all required, or perhaps some were added in the process of searching for the issue?

File: src/coreComponents/fileIO/Outputs/TimeHistoryOutput.cpp (hunk 2 above)
Comment (wrtobin) [reply src/coreComponents/fileIO/Outputs/TimeHistoryOutput.cpp:34]: I used it for debugging, but leaving it is also appropriate since it uses our standard logging mechanisms.

File: src/coreComponents/fileIO/Outputs/TimeHistoryOutput.cpp (hunk 1 above)
Comment (wrtobin) [reply src/coreComponents/fileIO/Outputs/TimeHistoryOutput.cpp:96]: the barriers are all required, yes. I added them incrementally. These specific ones mostly serve to reduce flock contention during initialization that resulted in long init times.

Comment (wrtobin) [reply src/coreComponents/fileIO/Outputs/TimeHistoryOutput.cpp:96]: In practice these should only improve general performance since the underlying calls are effectively barriers on subsets of the comm anyway and the file system accesses/contention is much more costly. The issue was when the underlying subcomm barriers were disjoint.
