### PR TITLE
SourceFlux & RegionStatistics crash fixes

### LINKED ISSUE #2832: Crash when SourceFlux targets non-simulated region
Hello everyone, 

We were working on a water production grid with one producer box. 

This case was run with:
•	PANGEA-2 machine
•	gcc 8.3.0 compiler
•	the Geos version 99abae2

Geos crashed and I had this error: 

image

We figured out that we got this crash when a SourceFlux is applied on a Box that intersects with non-simulated region(s).

Here you'll find a minimal reproducing exemple: 

[SaltDome.zip](https://github.com/GEOS-DEV/GEOS/files/13428779/SaltDome.zip)

With the original case, we also encountered Floating Point Exceptions by adding extra region with fluid, but we didn't achieved to create a minimal reproducer yet.

### PR DESCRIPTION
**Pull request by MelReyCG**
This PR aims to prevent two crashes:

1. When a `SourceFlux` is targeting an empty set (typically when a `Box` is intersecting with a non-simulated region)
*Action: continue the code normally, output a message if `logLevel > 1`.*

2. When a region pore volume is left to zero (because it is not necessary to fill it to the user).
*Action: continue the code normally, output a message if `logLevel > 1`.*

### CODE REVIEW

File: src/coreComponents/physicsSolvers/fluidFlow/CompositionalMultiphaseStatistics.cpp [hunk 1]
```diff
@@ -347,9 +347,21 @@ void CompositionalMultiphaseStatistics::computeRegionStatistics( MeshLevel & mes
...
+    {
+      float invTotalUncompactedPoreVolume = 1.0 / regionStatistics.totalUncompactedPoreVolume;
+      regionStatistics.averagePressure *= invTotalUncompactedPoreVolume;
+      regionStatistics.averageTemperature *= invTotalUncompactedPoreVolume;
+    }
+    else
+    {
+      regionStatistics.averagePressure = 0.0;
+      regionStatistics.averageTemperature = 0.0;
+      GEOS_LOG_LEVEL_RANK_0( 1, getName() << ", " << regionNames[i]
```
Comment (untereiner) [inline src/coreComponents/physicsSolvers/fluidFlow/CompositionalMultiphaseStatistics.cpp:407]: averagePressure and averageTemperature are not 0.0.  They are undetermined. Is there a constant somewhere that says "undetermined" ? Should maybe be discussed yet before making progress towards 2d outputs ?

File: src/coreComponents/physicsSolvers/fluidFlow/SinglePhaseStatistics.cpp [hunk 2]
```diff
@@ -182,7 +182,16 @@ void SinglePhaseStatistics::computeRegionStatistics( MeshLevel & mesh,
...
     regionStatistics.totalPoreVolume = MpiWrapper::sum( regionStatistics.totalPoreVolume );
     regionStatistics.averagePressure = MpiWrapper::sum( regionStatistics.averagePressure );
-    regionStatistics.averagePressure /= regionStatistics.totalUncompactedPoreVolume;
+    if( regionStatistics.totalUncompactedPoreVolume > 0 )
+    {
+      regionStatistics.averagePressure /= regionStatistics.totalUncompactedPoreVolume;
+    }
+    else
+    {
+      regionStatistics.averagePressure = 0.0;
```
Comment (untereiner) [inline src/coreComponents/physicsSolvers/fluidFlow/SinglePhaseStatistics.cpp:191]: same here

File: src/coreComponents/physicsSolvers/fluidFlow/SinglePhaseBase.cpp [hunk 3]
```diff
@@ -1028,6 +1028,15 @@ void SinglePhaseBase::applySourceFluxBC( real64 const time_n,
       {
         return;
       }
+      if( !subRegion.hasWrapper( dofKey ) )
+      {
+        if( fs.getLogLevel() >= 1 )
+        {
+          GEOS_LOG_RANK( GEOS_FMT( "{}: trying to apply SourceFlux, but set named '{}' intesects with non-simulated region named '{}'.",
```
Comment (untereiner) [inline src/coreComponents/physicsSolvers/fluidFlow/SinglePhaseBase.cpp]: "inteRsects"

Comment (untereiner) [reply src/coreComponents/physicsSolvers/fluidFlow/SinglePhaseBase.cpp]: not sure I understand the "but set named {}" ... Did you try to say: "SourceFlux named '{}' intersects with non-simulated region named '{}'." It will not be applied there."

File: src/coreComponents/physicsSolvers/fluidFlow/CompositionalMultiphaseStatistics.cpp (hunk 1 above)
Comment (MelReyCG) [reply src/coreComponents/physicsSolvers/fluidFlow/CompositionalMultiphaseStatistics.cpp:407]: `NaN` ?

File: src/coreComponents/physicsSolvers/fluidFlow/SinglePhaseBase.cpp (hunk 3 above)
Comment (MelReyCG) [reply src/coreComponents/physicsSolvers/fluidFlow/SinglePhaseBase.cpp]: The "set" term here refer to the `targetSet` of the `SourceFlux` (= a `Box` in our case).

Comment (MelReyCG) [reply src/coreComponents/physicsSolvers/fluidFlow/SinglePhaseBase.cpp]: I can use the term "the targetSet" instead of just "set" to be clearer. The idea is to give as much information as possible.

Comment (untereiner) [reply src/coreComponents/physicsSolvers/fluidFlow/SinglePhaseBase.cpp]: 'but its targetSet named {}' ?

File: src/coreComponents/physicsSolvers/fluidFlow/CompositionalMultiphaseStatistics.cpp (hunk 1 above)
Comment (MelReyCG) [reply src/coreComponents/physicsSolvers/fluidFlow/CompositionalMultiphaseStatistics.cpp:407]: It could be dangerous.
What do you think @dkachuma ?

File: src/coreComponents/physicsSolvers/fluidFlow/SinglePhaseBase.cpp (hunk 3 above)
Comment (MelReyCG) [reply src/coreComponents/physicsSolvers/fluidFlow/SinglePhaseBase.cpp]: Ok!

File: src/coreComponents/physicsSolvers/fluidFlow/CompositionalMultiphaseStatistics.cpp (hunk 1 above)
Comment (dkachuma) [reply src/coreComponents/physicsSolvers/fluidFlow/CompositionalMultiphaseStatistics.cpp:407]: When the region has zero pore volume, zero average pressure and average temperature are reasonable (and usual) values. I wouldn't put `NaN`.

File: src/coreComponents/physicsSolvers/fluidFlow/SinglePhaseBase.cpp [hunk 4]
```diff
@@ -1028,6 +1028,15 @@ void SinglePhaseBase::applySourceFluxBC( real64 const time_n,
...
       }
+      if( !subRegion.hasWrapper( dofKey ) )
+      {
+        if( fs.getLogLevel() >= 1 )
+        {
+          GEOS_LOG_RANK( GEOS_FMT( "{}: trying to apply SourceFlux, but its targetSet named '{}' intersects with non-simulated region named '{}'.",
+                                   getDataContext(), setName, subRegion.getName() ) );
+        }
+        return;
+      }
```
Comment (dkachuma) [inline src/coreComponents/physicsSolvers/fluidFlow/SinglePhaseBase.cpp:1039]: I think we need something similar in `CompositionalMultiphaseBase::applySourceFluxBC`

**Review by dkachuma — APPROVED** [review]

**Comment by MelReyCG** [comment]
@dkachuma Do you think we need to run the `integratedTests` on this PR?

**Comment by TotoGaz** [comment]
> @dkachuma Do you think we need to run the `integratedTests` on this PR?

Don't guess, measure!

**Review by untereiner — APPROVED** [review]

**Comment by MelReyCG** [comment]
> > @dkachuma Do you think we need to run the `integratedTests` on this PR?
> 
> Don't guess, measure!

Glad to finally test the `integratedTests` CI :)

I've got this output at the end:
```
ATS END OF RUN STARTED December 12, 2023 08:44:59
    Status     : TestCase                              : Directory                                                 : Elapsed : Resources : TestStep  
    ---------- : ------------------------------------- : --------------------------------------------------------- : ------- : --------- : ----------
    FAIL CHECK : PoroElastic_permeableFault_smoke_01   : poroElasticCoupling/PoroElastic_permeableFault_smoke_01   : 0:00:05 : 0:00:05   : restartcheck
    FAIL CHECK : PoroElastic_impermeableFault_smoke_01 : poroElasticCoupling/PoroElastic_impermeableFault_smoke_01 : 0:00:05 : 0:00:05   : restartcheck
    ---------- : ------------------------------------- : --------------------------------------------------------- : ------- : --------- : ----------
```

Is it a fail @TotoGaz ?

**Comment by paveltomin** [comment]
> > > @dkachuma Do you think we need to run the `integratedTests` on this PR?
> > 
> > 
> > Don't guess, measure!
> 
> Glad to finally test the `integratedTests` CI :)
> 
> I've got this output at the end:
> 
> ```
> ATS END OF RUN STARTED December 12, 2023 08:44:59
>     Status     : TestCase                              : Directory                                                 : Elapsed : Resources : TestStep  
>     ---------- : ------------------------------------- : --------------------------------------------------------- : ------- : --------- : ----------
>     FAIL CHECK : PoroElastic_permeableFault_smoke_01   : poroElasticCoupling/PoroElastic_permeableFault_smoke_01   : 0:00:05 : 0:00:05   : restartcheck
>     FAIL CHECK : PoroElastic_impermeableFault_smoke_01 : poroElasticCoupling/PoroElastic_impermeableFault_smoke_01 : 0:00:05 : 0:00:05   : restartcheck
>     ---------- : ------------------------------------- : --------------------------------------------------------- : ------- : --------- : ----------
> ```
> 
> Is it a fail @TotoGaz ?

These two cases are expected to fail currently. You can select "no rebaseline" and move to the merge queue.

**Comment by MelReyCG** [comment]
Ok, thanks!
