### PR TITLE
Simulation duration output fix + timestep separator

### LINKED ISSUE #2863: Incorrect run time in log for simulations over 24 hours
**Describe the bug**
The "run time" and "total time" at the end of the log are wrong when the simulation lasts more than a day. Only the hours are shown.

**To Reproduce**
Launch a simulation taking more than 24 hours and observe the run time shown at the end of the log, with no mention of the number of days.

**Expected behavior**
The log should show correct information on run time, with days/hours/minutes/seconds.

**Screenshots**
Run launched on Thu Nov 23 15:56, end at Fri Dec 11:41 (information from the job scheduler).
Here is the computed time in the job scheduler:
image
Which corresponds to 7 days 19 hours and 45 minutes.
Here is what is shown in the log, with only the hours:
image

### PR DESCRIPTION
**Pull request by MelReyCG**
This PR aims to:
- Fix the ending simulation duration output which were unable to show the passed days (when exceeding 24h, the output restarted to 0),
- Add a new timestep separator, which, in comparison with the previous one, is more visible than and readable for the users. This is a WIP and is subject to change later.
The old timestep output is temporarily kept in order to keep compatibility with log reading scripts that are currently in use to read the GEOS outputs.

Merging this PR will close the issue #2863

The ending duration output proposed is of the following form:
```
For 111 nanoseconds :              (old)        run time 00:00:00.0000001
                                   (new)        run time 00h00m00s (1.11e-07 s)

For 111 milliseconds :             (old)        run time 00:00:00.1110000
                                   (new)        run time 00h00m00s (0.111 s)

For 2min, 25s, 16ms :              (old)        run time 00:02:25.0160000
                                   (new)        run time 00h02m25s (145.016 s)

For 22h, 25min, 45s, 16ms :        (old)        run time 22:25:45.0160000
                                   (new)        run time 22h25m45s (80745.016 s)

For 20j, 12h, 2min, 25s :          (old)        run time 12:02:25.0000000
                                   (new)        run time 20d, 12h02m25s (1771345 s)

For 1 an, 20j, 12h, 2min, 25s :    (old)        run time 17:51:37.0000000
                                   (new)        run time 1y, 20d, 12h02m25s (33328297 s)

For 292 ans, 20j, 12h, 2min, 25s : (old)        run time 07:28:49.0000000
                                   (new)        run time 292y, 20d, 12h02m25s (9216401329 s)
```

This PR proposes new components in the `units` namespace:
- `units::TimeFormatInfo` which is the intermediate structure to format durations (it is needed as there was no satisfying solution with `std`/`fmt` formatters),
- A few time constants. One of them is `units::YearDays`, which value is `365.2425`, following the [C++20 standard](https://en.cppreference.com/w/cpp/chrono/duration),
- Alias types `units::Days` and `units::Years` are added, and compatible with `std::chono` functionnalities.

This PR also includes tests.

### CODE REVIEW

**Review by untereiner — APPROVED** [review]

**Comment by MelReyCG** [comment]
@TotoGaz Do we need to run the integratedTests on this PR?

**Comment by MelReyCG** [comment]
Integrated tests ran without issue:
```
ATS END OF RUN STARTED December 12, 2023 16:44:11
    Status     : TestCase                              : Directory                                                 : Elapsed : Resources : TestStep  
    ---------- : ------------------------------------- : --------------------------------------------------------- : ------- : --------- : ----------
    FAIL CHECK : PoroElastic_permeableFault_smoke_01   : poroElasticCoupling/PoroElastic_permeableFault_smoke_01   : 0:00:05 : 0:00:05   : restartcheck
    FAIL CHECK : PoroElastic_impermeableFault_smoke_01 : poroElasticCoupling/PoroElastic_impermeableFault_smoke_01 : 0:00:05 : 0:00:05   : restartcheck
    ---------- : ------------------------------------- : --------------------------------------------------------- : ------- : --------- : ----------
```

**Comment by MelReyCG** [comment]
Hello @paveltomin , would you like to review this PR? The users of my team like the new layout, but I would like a second opinion from a developer.
(you may have already looked the changes as you added the `ready to be merged` label)

File: src/coreComponents/events/EventManager.cpp [hunk 1]
```diff
@@ -224,39 +226,48 @@ bool EventManager::run( DomainPartition & domain )
 
 void EventManager::outputTime() const
 {
+  // The formating here is a work in progress.
+  GEOS_LOG_RANK_0( GEOS_FMT( "\n"
```
Comment (paveltomin) [inline src/coreComponents/events/EventManager.cpp:230]: why this duplicates the output below?
i don't really like multi-line output in general, harder to filter out for no big reason

Comment (MelReyCG) [reply src/coreComponents/events/EventManager.cpp:230]: I explained that in the description: The old timestep output is temporarily kept in order to keep compatibility with log reading scripts that are currently in use to read the GEOS outputs.

This old output is to considered as deprecated, it will be removed later.

File: src/coreComponents/events/EventManager.cpp [hunk 2]
```diff
@@ -224,39 +226,48 @@ bool EventManager::run( DomainPartition & domain )
...
+                             "------------------- TIMESTEP START -------------------\n"
```
Comment (paveltomin) [inline src/coreComponents/events/EventManager.cpp:231]:
```
------------------- TIMESTEP START -------------------
    - Time:       -3168y, -319d, -4h-1m-4s (-100000000000 s)
    - Delta Time: 3168y, 319d, 04h01m04s (100000000000 s)
    - Cycle:      0
------------------------------------------------------
```
@MelReyCG see the output above and could you please double check that conversion to h-m-s works correct?
