### PR TITLE
fix: compilation error with Apple Clang

### LINKED ISSUE #3771: AppleClang Compiler issue with template signature
I get a `error: a template argument list is expected after a name prefixed by the template keyword [-Wmissing-template-arg-list-after-template-kw]` error when compiling.

**Platform:**
- Machine : Apple M1
- Compiler: Apple clang version 17.0.0 (clang-1700.0.13.5), Target: arm64-apple-darwin24.6.0, Thread model: posix
- GEOS Hash 9142e888e5

### PR DESCRIPTION
**Pull request by herve-gross**
This fixes an error I am having with my compiler. Thanks @dkachuma for the tip. It fixes issue #3771 .

### CODE REVIEW

File: src/coreComponents/physicsSolvers/multiphysics/PoromechanicsSolver.hpp [hunk 1]
```diff
@@ -190,7 +190,7 @@ class PoromechanicsSolver : public CoupledSolver< FLOW_SOLVER, MECHANICS_SOLVER
       flowSolver()->enableJumpStabilization();
     }
 
-    this->template forDiscretizationOnMeshTargets( meshBodies, [&] ( string const &,
+    this->forDiscretizationOnMeshTargets( meshBodies, [&] ( string const &,
                                                                      MeshLevel & mesh,
                                                                      string_array const & regionNames )
```
Comment (jhuang2601) [inline src/coreComponents/physicsSolvers/multiphysics/PoromechanicsSolver.hpp]:
```suggestion
    this->forDiscretizationOnMeshTargets( meshBodies, [&] ( string const &,
                                                            MeshLevel & mesh,
                                                            string_array const & regionNames )
```

File: src/coreComponents/physicsSolvers/multiphysics/PoromechanicsSolver.hpp [hunk 2]
```diff
@@ -444,7 +444,7 @@ class PoromechanicsSolver : public CoupledSolver< FLOW_SOLVER, MECHANICS_SOLVER
                                               array1d< real64 > & averageMeanTotalStressIncrement )
   {
     averageMeanTotalStressIncrement.resize( 0 );
-    this->template forDiscretizationOnMeshTargets( domain.getMeshBodies(), [&]( string const &,
+    this->forDiscretizationOnMeshTargets( domain.getMeshBodies(), [&]( string const &,
                                                                                 MeshLevel & mesh,
                                                                                 string_array const & regionNames )
```
Comment (jhuang2601) [inline src/coreComponents/physicsSolvers/multiphysics/PoromechanicsSolver.hpp]:
```suggestion
    this->forDiscretizationOnMeshTargets( domain.getMeshBodies(), [&]( string const &,
                                                                       MeshLevel & mesh,
                                                                       string_array const & regionNames )
```

File: src/coreComponents/physicsSolvers/multiphysics/PoromechanicsSolver.hpp [hunk 3]
```diff
@@ -470,7 +470,7 @@ class PoromechanicsSolver : public CoupledSolver< FLOW_SOLVER, MECHANICS_SOLVER
                                                         array1d< real64 > & averageMeanTotalStressIncrement )
   {
     integer i = 0;
-    this->template forDiscretizationOnMeshTargets( domain.getMeshBodies(), [&]( string const &,
+    this->forDiscretizationOnMeshTargets( domain.getMeshBodies(), [&]( string const &,
                                                                                 MeshLevel & mesh,
                                                                                 string_array const & regionNames )
```
Comment (jhuang2601) [inline src/coreComponents/physicsSolvers/multiphysics/PoromechanicsSolver.hpp]:
```suggestion
    this->forDiscretizationOnMeshTargets( domain.getMeshBodies(), [&]( string const &,
                                                                       MeshLevel & mesh,
                                                                       string_array const & regionNames )
```

**Review by paveltomin — APPROVED** [review]

**Review by jhuang2601 — APPROVED** [review]

**Review by dkachuma — APPROVED** [review]

**Comment by paveltomin** [comment]
good to move into merge queue?

**Comment by herve-gross** [comment]
For me, yes, but the CI seems to have errors (and I do not know why)

**Comment by paveltomin** [comment]
> For me, yes, but the CI seems to have errors (and I do not know why)

just needs "ci: run integrated tests" label

**Comment by OmarDuran** [comment]
@paveltomin this is ready to be merged.
