### PR TITLE
fix: enable FullyImplicit for SinglePhaseReservoirPoromechanicsConformingFractures

### LINKED ISSUE #3850: Crash when switching from Sequential to FullyImplicit in fault model test case
[contact.mechanics.zip](https://github.com/user-attachments/files/22732203/contact.mechanics.zip)

[fracture.out.txt](https://github.com/user-attachments/files/22732218/fracture.out.txt)

**Describe the bug**  
Switching the solver mode from `Sequential` to `FullyImplicit` in the GEOS integrated test case causes a crash due to a missing finite volume discretization. The same test case runs successfully in `Sequential` mode.

**To Reproduce**  
1. Attached [case](https://github.com/user-attachments/files/22732203/contact.mechanics.zip) is based on the integrated test [singlePhasePoromechanics_FaultModel_well_seq_new_smoke.xml](https://github.com/GEOS-DEV/GEOS/blob/develop/inputFiles/poromechanicsFractures/singlePhasePoromechanics_FaultModel_well_seq_new_smoke.xml)
2. Run the test case.
3. Observe the crash and error message related to missing finite volume discretization.

**Expected behavior**  
The test case should run successfully in `FullyImplicit` mode, similar to its behavior in `Sequential` mode, without requiring additional discretization definitions.

**Platform (please complete the following information):**
- Machine: pine  
- Compiler: gcc 12.2.0  
- GEOS Version: 1.1.0 (develop, sha1: 3a78f14560)

**Additional context**  
This issue appears to be specific to the solver mode switch. The test case is part of the poromechanics fracture suite and is used to validate fault model behavior. The crash suggests that the `FullyImplicit` mode may require additional configuration or discretization setup that is not needed in `Sequential` mode.

### PR DESCRIPTION
**Pull request by paveltomin**
should fix https://github.com/GEOS-DEV/GEOS/issues/3850

fixes are:
1) assign discretization name for coupled reservoir and wells solver (causes rebaseline)
2) create a version of assembleSystem for SinglePhasePoromechanicsConformingFractures that has well parts assembly (similar to SinglePhasePoromechanics)

the rest of the changes is cleanup - move code to parent class where possible to avoid duplication

### CODE REVIEW

**Comment by paveltomin** [comment]
Ready for review

**Review by dkachuma — APPROVED** [review]
Looks good to me. This is also done for multiphase, right?

**Comment by paveltomin** [comment]
> Looks good to me. This is also done for multiphase, right?

Once wells are enabled for multiphase, similar version of assembleSystem function needs to be added there, not done yet in this PR

File: src/coreComponents/physicsSolvers/multiphysics/CoupledReservoirAndWellsBase.hpp [hunk 1]
```diff
@@ -181,6 +181,9 @@ class CoupledReservoirAndWellsBase : public CoupledSolver< RESERVOIR_SOLVER, WEL
   {
     Base::postInputInitialization();
 
+    // assume that reservoir solver discretization is the primary one
+    this->m_discretizationName = reservoirSolver()->getDiscretizationName();
```
Comment (paveltomin) [inline src/coreComponents/physicsSolvers/multiphysics/CoupledReservoirAndWellsBase.hpp:185]: this is first fix

File: src/coreComponents/physicsSolvers/multiphysics/SinglePhasePoromechanicsConformingFractures.cpp [hunk 2]
```diff
@@ -225,6 +225,23 @@ assembleFluidMassResidualDerivativeWrtDisplacement( MeshLevel const & mesh,
...
+                DomainPartition & domain,
+                DofManager const & dofManager,
+                CRSMatrixView< real64, globalIndex const > const & localMatrix,
+                arrayView1d< real64 > const & localRhs )
+{
+  GEOS_MARK_FUNCTION;
+
+  Base::assembleSystem( time_n, dt, domain, dofManager, localMatrix, localRhs );
+
+  // assemble well contributions
```
Comment (paveltomin) [inline src/coreComponents/physicsSolvers/multiphysics/SinglePhasePoromechanicsConformingFractures.cpp:241]: this is second fix

**Review by jhuang2601 — APPROVED** [review]

**Comment by paveltomin** [comment]
@castelletto1 @OmarDuran @frankfeifan @Guotong-Ren review please

**Review by castelletto1 — APPROVED** [review]
Looks good to me, thanks.
