### PR TITLE
feat: Adding possibility to output all TableFunction in log/CSV + Solving a bug on PVT CSV export

### LINKED ISSUE #3412: writeCSV attribute not valid
Hello,

I am running GEOSX Version 0.2.0 and I am attempting to use the 'writeCSV' attribute in the XML Element CompositionalMultiphaseStatistics:
https://geosx-geosx.readthedocs-hosted.com/en/latest/docs/sphinx/datastructure/CompleteXMLSchema.html#xml-element-compositionalmultiphasestatistics

and the XML Element CompositionalMultiphaseWell:
https://geosx-geosx.readthedocs-hosted.com/en/latest/docs/sphinx/datastructure/CompleteXMLSchema.html#xml-element-compositionalmultiphasewell

This is listed as an allowable attribute for these elements per the datastructure index in the GEOS documentation. However, when I include this attribute with a level of 1 on either element in the input file and run it, GEOS fails and says 'writeCSV' is an unused attribute and lists the valid attributes, which match the datastructure index minus writeCSV. Has this attribute been removed from the datastructure? This is an issue because other than interfacing with python, this is the only way I am aware of to obtain formatted output from GEOS. The console text file output log is formatted such that each result is a single string of characters and this makes post-processing exceedingly tedious without python.

Any help is much appreciated. Thanks in advance!

### PR DESCRIPTION
**Pull request by MelReyCG**
This PR aims to:

1. Add the possibility to write `TableFunction`s in the log or in a CSV file through `logLevel="1"` or `writeCSV="1"` (this feature has been requested by TE users),

2. Allow to create tables without layout specification (added a test to illustrate, the goal is to allow to create table without headers, with only data rows)

3. Slightly refactor the `TableFunction` code to remove any PVT concept from its class,

4. Slightly rewrite the `writeCSV` documentation to make it clearer,

5. Add the table coordinates/values min, max and unit metadata at the top of the table,
image

6. For 2D tables, used standard variables to produce narrower output lines (and ensured that the first coordinate is on the X axis),
image

7. Unify the CSV generation when a table is too big and move the warning message inside the table, while keep showing its metadata.
image

----

This PR also solves bugs:
1. on saving a PVT, `SinglePhaseWell` and `CompositionalMultiphaseWell` table to a CSV file when an output folder has not been created yet (lacking `makeDirsForPath()` call),

2. A crash on table generation

3. wrong behaviour of merged cell when they share the same column, and are wider than them:
```
----------------------------------------------------------------------------------------------------------------
|                                                 Lorem Ipsum                                                  |
----------------------------------------------------------------------------------------------------------------
|      A       |      B       |      C       |  X  |      A       |      B       |      C       |      C       |
----------------------------------------------------------------------------------------------------------------
|  0123456789  |  0123456789  |  0123456789  |  X  |  0123456789  |  0123456789  |  0123456789  |  0123456789  |
|  0123456789  |  012345678901234567890123456789  |  X  |  0123456789  |  0123456789  |  0123456789  |  0123456789  |
|  012345678901234567890123456789  |  0123456789  |  X  |  0123456789  |  0123456789  |  0123456789  |  0123456789  |
|  0123456789  |  0123456789  |  0123456789  |  X  |  0123456789  |  0123456789  |  0123456789  |  0123456789  |
|  0123456789  |  0123456789  |  0123456789  |  X  |  01234567890123456789012345678901234567890123456789  |  0123456789  |
|  0123456789  |  0123456789  |  0123456789  |  X  |  0123456789  |  01234567890123456789012345678901234567890123456789  |
|  0123456789  |  0123456789  |  0123456789  |  X  |  0123456789  |  0123456789  |  0123456789  |  0123456789  |
----------------------------------------------------------------------------------------------------------------\
```
which will now give:
```
---------------------------------------------------------------------------------------------------------------------------------
|                                                          Lorem Ipsum                                                          |
---------------------------------------------------------------------------------------------------------------------------------
|       A       |        B         |       C       |  X  |       A       |         B         |        C         |       C       |
---------------------------------------------------------------------------------------------------------------------------------
|   0123456789  |      0123456789  |   0123456789  |  X  |   0123456789  |       0123456789  |      0123456789  |   0123456789  |
|   0123456789  |  012345678901234567890123456789  |  X  |   0123456789  |       0123456789  |      0123456789  |   0123456789  |
|  012345678901234567890123456789  |   0123456789  |  X  |   0123456789  |       0123456789  |      0123456789  |   0123456789  |
|   0123456789  |      0123456789  |   0123456789  |  X  |   0123456789  |       0123456789  |      0123456789  |   0123456789  |
|   0123456789  |      0123456789  |   0123456789  |  X  |  01234567890123456789012345678901234567890123456789  |   0123456789  |
|   0123456789  |      0123456789  |   0123456789  |  X  |   0123456789  |  01234567890123456789012345678901234567890123456789  |
|   0123456789  |      0123456789  |   0123456789  |  X  |   0123456789  |       0123456789  |      0123456789  |   0123456789  |
---------------------------------------------------------------------------------------------------------------------------------
```

----

better column continuity through the horizontal separators:
```
--------------------------------------------------      --------------------------------------------------|
|         Nodes         |          Faces         |      |         Nodes         |          Faces          |
--------------------------------------------------      |-----------------------|-------------------------|
| Local | Ghost | Total | Local  | Ghost| Total  |      | Local | Ghost | Total | Local  | Ghost | Total  |
--------------------------------------------------      |-------|-------|-------|--------|-------|--------|
| 9,201 |   0   | 9,201 | 99,784 |   0  | 99,784 |      | 9,201 |   0   | 9,201 | 99,784 |   0   | 99,784 |
--------------------------------------------------  ->  |-------|-------|-------|--------|-------|--------|
| 9,201 |   0   | 9,201 | 99,784 |   0  | 99,784 |      | 9,201 |   0   | 9,201 | 99,784 |   0   | 99,784 |
| 9,201 |   0   | 9,201 | 99,784 |   0  | 99,784 |      | 9,201 |   0   | 9,201 | 99,784 |   0   | 99,784 |
| 9,201 |   0   | 9,201 | 99,784 |   0  | 99,784 |      | 9,201 |   0   | 9,201 | 99,784 |   0   | 99,784 |
--------------------------------------------------      |-----------------------|-------------------------|
|           1           |            1           |      |           1           |            1            |
|           1           |            1           |      |           1           |            1            |
--------------------------------------------------      ---------------------------------------------------
```
----

Sorry to include such scattered work in the PR, but they are all small changes for tables output in log/csv.

----

Last things left to do to finish this PR for review:
- [x] clearer warning when a table is not displayed + link inside the table
- [x] headers for non-2D CSV columns to be reviewed
- [x] limit table HEIGHT and WIDTH
- [x] display 3D (or more) tables in log
- [x] In depth refactor to solve the merging bug, and have a clearer/faster code, and that does not cheat with constness.
- [x] better column continuity through the separators
- [x] real support for tables without layout specification (added a test to illustrate, the goal is to allow to create table without headers)

### CODE REVIEW

**Comment by MelReyCG** [comment]
Currently, 
- documentation is not completed, 
- table layout is not optimal.
```
---------------------------------
|        totalRateTable         |
---------------------------------
|  unknown [?]  |  unknown [?]  |
---------------------------------
|            0  |         0.03  |
|    160000000  |            0  |
|    500000000  |            0  |
---------------------------------
```

I'm working on polishing these last points.

**Review by arng40 — APPROVED** [review]

**Review by paveltomin — APPROVED** [review]

**Comment by MelReyCG** [comment]
I'm also adding a bugfix for issue [3412](https://github.com/GEOS-DEV/GEOS/issues/3412)

File: src/coreComponents/common/format/table/TableFormatter.cpp [hunk 1]
```diff
@@ -577,31 +586,29 @@ void TableTextFormatter::adjustColumnWidth( CellLayoutRows & cells,
       }
     }
   }
-
 }
 
 void TableTextFormatter::outputTitleRow( TableLayout & tableLayout,
```
Comment (arng40) [inline src/coreComponents/common/format/table/TableFormatter.cpp]: thanks for the multiline support 🙂

File: src/coreComponents/functions/FunctionBase.cpp [hunk 2]
```diff
@@ -81,6 +82,12 @@ void FunctionBase::setOutputDirectory( string const & dir )
 {
   string & outputDirectory = const_cast< string & >( getOutputDirectory() );
   outputDirectory = dir;
+
+  if( MpiWrapper::commRank( MPI_COMM_GEOS ) == 0 )
+  {
+    makeDirsForPath( dir );
+  }
+  MpiWrapper::barrier( MPI_COMM_GEOS );
```
Comment (arng40) [inline src/coreComponents/functions/FunctionBase.cpp]: is it useful ?

File: src/coreComponents/common/format/table/TableFormatter.cpp (hunk 1 above)
Comment (MelReyCG) [reply src/coreComponents/common/format/table/TableFormatter.cpp]: ✌️

File: src/coreComponents/common/format/table/TableFormatter.cpp [hunk 3]
```diff
@@ -194,16 +194,17 @@ void TableTextFormatter::initalizeTableLayout( TableLayout & tableLayout,
 
   updateColumnMaxLength( tableLayout, cellsHeaderLayout, cellsDataLayout );
 
-  adjustTableWidth( tableLayout, cellsHeaderLayout, cellsDataLayout, separatorLine, nbEnabledColumn );
+  adjustTableWidth( tableLayout, cellsHeaderLayout, cellsDataLayout, tableTotalWidth, nbEnabledColumn );
 }
```
Comment (MelReyCG) [inline src/coreComponents/common/format/table/TableFormatter.cpp:201]:
```
  // 
  tableTotalWidth = tableLayout.getBorderMargin() * 2 + 2;
  for( size_t columnId = 0; columnId < referenceRow.size(); ++columnId )
  {
    tableTotalWidth += referenceRow[columnId].m_cellWidth + size_t( columnId > 0 ? tableLayout.getColumnMargin() : 0 );
    nbEnabledColumn += ( referenceRow[columnId].m_cellType != CellType::Hidden ? 1 : 0 );
  }
```
@arng40 is this right to compute this way? `(TableTextFormatter::initalizeTableGrids())`

Comment (arng40) [reply src/coreComponents/common/format/table/TableFormatter.cpp:201]: As long as you take into account all the margin and only the enabled column, sure

Comment (MelReyCG) [reply src/coreComponents/common/format/table/TableFormatter.cpp:201]: so the comment in getBorderMargin() seems wrong, as for `|  abc  |` I get 2.

**Review by paveltomin — APPROVED** [review]

File: src/coreComponents/common/format/table/TableFormatter.cpp [hunk 4]
```diff
@@ -157,549 +137,449 @@ template<>
...
 
-            formatCell( tableLayout, tableOutput, cell, idxSubLine );
+          if( isLeftBorderCell )
+          { // left table border
+            isLeftBorderCell=false;
+            tableOutput << m_verticalLine << string( nbBorderSpaces, cellSpaceChar );
+          }
+          else
+          { // left side of a cell that have a neightboor
+            tableOutput << string( nbColumnSpaces, cellSpaceChar ); // à faire si on a pas été mergé avec la gauche toute
```
Comment (arng40) [inline src/coreComponents/common/format/table/TableFormatter.cpp]: forgotten comment

File: src/coreComponents/common/format/StringUtilities.cpp [hunk 5]
```diff
@@ -205,6 +148,84 @@ template string toMetricPrefixString( unsigned long long int const & );
 template string toMetricPrefixString( float const & );
 template string toMetricPrefixString( double const & );
 
+template< typename STRING_T >
+std::vector< STRING_T > divideLines( size_t & linesWidth, string_view value )
```
Comment (arng40) [inline src/coreComponents/common/format/StringUtilities.cpp:152]: move to stringutilities ?

File: src/coreComponents/common/format/table/TableFormatter.cpp [hunk 6]
```diff
@@ -157,549 +137,449 @@ template<>
...
+  populateDataCellsLayout( tableLayout, dataCellsLayout, inputDataValues, referenceRow.cells.size() );
 
-  updateColumnMaxLength( tableLayout, cellsHeaderLayout, cellsDataLayout );
+  stretchRowToCellsWidth( referenceRow, headerCellsLayout );
+  stretchRowToCellsWidth( referenceRow, dataCellsLayout );
 
-  adjustTableWidth( tableLayout, cellsHeaderLayout, cellsDataLayout, separatorLine, nbEnabledColumn );
-}
+  // after that, we can process the merged cells.
+  stretchRowToMergedCellsWidth( referenceRow, headerCellsLayout, tableLayout, false );
```
Comment (arng40) [inline src/coreComponents/common/format/table/TableFormatter.cpp]: why do you call this function with headerCellsLayout, we'll never have a merge cell in headers, will we?  Am I missing something ?

File: src/coreComponents/common/format/table/TableFormatter.cpp [hunk 7]
```diff
@@ -37,37 +37,35 @@ TableFormatter::TableFormatter( TableLayout const & tableLayout ):
...
+static constexpr string_view csvSeparator = ",";
 string TableCSVFormatter::headerToString() const
 {
   string result;
 
   size_t total_size = 0;
   for( const auto & column : m_tableLayout.getColumns())
   {
-    for( const auto & str : column.m_header.m_lines )
+    for( const auto & str : column.m_headerLayout.m_lines )
```
Comment (arng40) [inline src/coreComponents/common/format/table/TableFormatter.cpp]: auto const

File: src/coreComponents/common/format/StringUtilities.cpp (hunk 5 above)
Comment (MelReyCG) [reply src/coreComponents/common/format/StringUtilities.cpp:152]: yes, I think it can be useful for someone else.

File: src/coreComponents/common/format/table/TableFormatter.cpp (hunk 6 above)
Comment (MelReyCG) [reply src/coreComponents/common/format/table/TableFormatter.cpp]: I think so. For this exemple:
```
----------------------------------------------------------
|        Rank        |             Nodes                 |
|                    |                                   |
----------------------------------------------------------
|                    |    Count local    |  Count ghost  |
|                    |  active elements  |   elemnt n    |
|                    |                   |               |
----------------------------------------------------------
```
... here a view is the internal data of `CellLayoutRows & headerCellsLayout` : 
- `t` being the `m_cellType`,
- `w` being the `m_cellWidth`,
```
----------------------------------------------------------
|       "Rank"       |        ""         |     "Nodes"   |
|  (t=Header, w=4)   |(t=MergeNext, w=0) |(t=Header, w=5)|
----------------------------------------------------------
|        ""          |   "Count local"   | "Count ghost" |
|                    | "active elements" |   "elemnt n"  |
|    (t=Header, w=0) |  (t=Header, w=15) |(t=Header,w=11)|
----------------------------------------------------------
```

Is it clear enough?

File: src/coreComponents/common/format/table/TableFormatter.cpp (hunk 4 above)
Comment (MelReyCG) [reply src/coreComponents/common/format/table/TableFormatter.cpp]: removed

File: src/coreComponents/common/format/table/TableFormatter.cpp (hunk 7 above)
Comment (MelReyCG) [reply src/coreComponents/common/format/table/TableFormatter.cpp]: switched

File: src/coreComponents/common/format/table/TableFormatter.cpp (hunk 6 above)
Comment (MelReyCG) [reply src/coreComponents/common/format/table/TableFormatter.cpp]: added a note to populateHeaderCellsLayout

Comment (arng40) [reply src/coreComponents/common/format/table/TableFormatter.cpp]: oh ok I see, thanks for the doc clarification

**Review by arng40 — APPROVED** [review]

**Review by dkachuma — APPROVED** [review]

**Review by arng40 — APPROVED** [review]

**Review by arng40 — APPROVED** [review]

File: src/coreComponents/common/format/table/TableFormatter.cpp [hunk 8]
```diff
@@ -157,553 +141,526 @@ template<>
...
-
-  populateHeaderCellsLayout( tableLayout, cellsHeaderLayout );
+  bool const hasColumnLayout = !tableLayout.getColumns().empty();
+  RowsCellInput const & inputDataValues( tableInputData.getTableDataRows() );
+  size_t const inputDataRowsCount = !inputDataValues.empty() ? inputDataValues.front().size() : 0;
 
-  RowsCellInput inputDataValues( tableData.getTableDataRows());
-  if( inputDataValues.size() > 0 )
+  populateHeaderCellsLayout( tableLayout, headerCellsLayout, inputDataRowsCount );
+  if( hasColumnLayout )
```
Comment (arng40) [inline src/coreComponents/common/format/table/TableFormatter.cpp]: I'm wondering if we can add populateTitleLayout(), i.e extract this code :
```
  // we add the title, as a first row with all cells merged in one containing the title text
  if( hasTitle )
  {
    CellLayout const & inputTitleCell = tableLayout.getTitleLayout();
    CellLayoutRow & titleRow = headerCellsLayout[0];
    // we setup a row of cells merging with the last cell containing the title
    titleRow = {
      std::vector< CellLayout >( headerCellsLayout[1].cells.size(),
                                 CellLayout( CellType::MergeNext ) ),              // cells
      inputTitleCell.m_lines.size() // sublinesCount
    };
    titleRow.cells.back() = inputTitleCell;
  }
```
 this way we can just do 
 
```
if(hasColumnLayout)
    populateHeaderCellsLayout( tableLayout, headerCellsLayout, inputDataRowsCount );
```

and in TableFormatter we can just do :
  ```
   size_t const headerColumnsCount = tableLayout.getLowermostColumnsCount()
  ```

File: src/coreComponents/functions/FunctionBase.cpp (hunk 2 above)
Comment (MelReyCG) [reply src/coreComponents/functions/FunctionBase.cpp]: nope, commented

File: src/coreComponents/common/format/table/TableFormatter.cpp (hunk 8 above)
Comment (MelReyCG) [reply src/coreComponents/common/format/table/TableFormatter.cpp]: Nice suggestion, this populating process will more robust and it will be useful later to have them uncoupled, let me know if commit 50e17393cd5907bf27baf19bd04105a4d5e4934b properly follows your recommendation.

File: src/coreComponents/common/format/table/TableFormatter.cpp [hunk 9]
```diff
@@ -157,553 +141,533 @@ template<>
...
+        { // we detected a set of cells to merge, let's compute its total width
+          size_t mergedColumnsWidth = currentColumnWidth;
+          for( size_t mergedId = columnId + 1; mergedId < numColumns; mergedId++ )
           {
-            updateCellMaxLength( cellsDataLayout[rowIdx2][idxColumn], maxColumnSize );
-            if( cellsDataLayout[rowIdx2][idxColumn].m_cellType == CellType::Separator )
+            TableLayout::CellLayout const & mergedCell = row.cells[mergedId];
+            mergedColumnsWidth += referenceRow.cells[mergedId].m_cellWidth + flexSpaces[mergedId];
+            mergedColumnsWidth += spaceBetweenColumns;
+            if( mergedCell.m_cellType != CellType::MergeNext || columnId == numColumns - 1 )
```
Comment (arng40) [inline src/coreComponents/common/format/table/TableFormatter.cpp]: Found 2 bug in the table : 

- First thing first is when we only have 1 line in TableData and set this way :

```
 TableData tableData;
  tableData.addRow( 1500, CellType::MergeNext, CellType::MergeNext, CellType::MergeNext, CellType::MergeNext, CellType::MergeNext );
```
The table is not being formatted and this has to do with this part because I think oversize is never reassign

File: src/coreComponents/common/format/table/TableFormatter.cpp [hunk 10]
```diff
@@ -157,553 +141,533 @@ template<>
...
+    size_t nbVisibleColumns = headerCellsLayout.back().cells.size();
+    populateDataCellsLayout( tableLayout, dataCellsLayout, inputDataValues, nbVisibleColumns );
+  }
+  else
+  {
+    populateDataCellsLayout( tableLayout, dataCellsLayout, inputDataValues );
   }
 
-  updateColumnMaxLength( tableLayout, cellsHeaderLayout, cellsDataLayout );
+  // this reference row will store the displayed number & width of all columns (and will be stretched by data & headers)
```
Comment (arng40) [inline src/coreComponents/common/format/table/TableFormatter.cpp]: - When we don't have a tableLayout, the reference row will be the front of TableData, but if we set different values to the first tableData the table output will be badly shaped.

```
  TableData tableData;
  tableData.addRow( "ProductB", CellType::MergeNext, 40, CellType::Hidden );
  tableData.addRow( "ProductA", 12345678, 159812312323123, "ProductName" );
  tableData.addSeparator();
  tableData.addRow( CellType::MergeNext, CellType::MergeNext, CellType::MergeNext, 40)
```

**Review by arng40 — CHANGES_REQUESTED** [review]

File: src/coreComponents/common/format/table/TableFormatter.cpp (hunk 9 above)
Comment (MelReyCG) [reply src/coreComponents/common/format/table/TableFormatter.cpp]: Nice catch!

**Review by arng40 — APPROVED** [review]

**Comment by herve-gross** [comment]
@wrtobin @cssherman @CusiniM can you review this? Thanks!

File: .integrated_tests.yaml [hunk 11]
```diff
@@ -1,6 +1,6 @@
 baselines:
   bucket: geosx
-  baseline: integratedTests/baseline_integratedTests-pr3396-10875-13b594f
+  baseline: integratedTests/baseline_integratedTests-pr3537-10887-9327e03
```
Comment (CusiniM) [inline .integrated_tests.yaml]: you ll have to redo this.

File: src/coreComponents/common/CMakeLists.txt [hunk 12]
```diff
@@ -138,6 +138,16 @@ blt_add_library( NAME       common
 target_include_directories( common PUBLIC ${CMAKE_BINARY_DIR}/include )
 target_include_directories( common PUBLIC ${CMAKE_SOURCE_DIR}/coreComponents )
 
+# Older g++ version need a hint to use std::filesystem
+if( CMAKE_CXX_COMPILER_ID STREQUAL "GNU" )
+    if( CMAKE_CXX_COMPILER_VERSION VERSION_LESS 9 )
```
Comment (CusiniM) [inline src/coreComponents/common/CMakeLists.txt:143]: seems an okay workaround but do we need to support versions of gcc older than 9?

File: src/coreComponents/common/CMakeLists.txt [hunk 13]
```diff
@@ -138,6 +138,16 @@ blt_add_library( NAME       common
...
+        target_link_libraries( common PRIVATE "stdc++fs" )
+    endif ()
+endif ()
+if ( ENABLE_CUDA )
```
Comment (CusiniM) [inline src/coreComponents/common/CMakeLists.txt:147]: why would enabling `CUDA` imply this?

File: src/coreComponents/common/format/table/TableData.cpp [hunk 14]
```diff
@@ -50,34 +50,37 @@ std::vector< std::vector< TableData::CellData > > const & TableData::getTableDat
...
 {
-  integer const nX = rowAxisValues.size();
-  integer const nY = columnAxisValues.size();
-
-  for( integer i = 0; i < nX; i++ )
+  arraySlice1d< real64 const > rowAxisCoordinates = columnMajorInputValues ? dim1AxisCoordinates : dim0AxisCoordinates;
+  arraySlice1d< real64 const > columAxisCoordinates = columnMajorInputValues ? dim0AxisCoordinates : dim1AxisCoordinates;
+  integer const nCol = columAxisCoordinates.size();
+  integer const nRow = rowAxisCoordinates.size();
+  // TODO: 1. restore the table non-blocking error system. 2. add this assert 3. add any other error to it.
```
Comment (CusiniM) [inline src/coreComponents/common/format/table/TableData.cpp:62]: maybe open an issue.

**Review by CusiniM — APPROVED** [review]

File: src/coreComponents/common/format/table/TableData.cpp (hunk 14 above)
Comment (MelReyCG) [reply src/coreComponents/common/format/table/TableData.cpp:62]: Arnaud is working on this (and the other TODOs you can find in `common/format/table`) in `arng40/feature/table-errors-listing`, he will post a PR soon.

File: .integrated_tests.yaml (hunk 11 above)
Comment (MelReyCG) [reply .integrated_tests.yaml]: Is it because of future merges on develop? If not I don't understand why.

File: src/coreComponents/common/CMakeLists.txt (hunk 12 above)
Comment (MelReyCG) [reply src/coreComponents/common/CMakeLists.txt:143]: Since Pangea3 is still internally compiled with GCC 8.4, I would say so.

File: src/coreComponents/common/CMakeLists.txt (hunk 13 above)
Comment (MelReyCG) [reply src/coreComponents/common/CMakeLists.txt:147]: Without that, I had an issue with the Pangea 3 CI build (GCC 9.4).
Actually, this code is moved from the `unitTests/meshTests` package, I needed to move it in `common` to add functionnalities to `Path.xpp`.

**Review by wrtobin — APPROVED** [review]
