### PR TITLE
Fix for black oil

### LINKED ISSUE #2664: "NotConverged" in linear solver
1. Take this case: https://github.com/GEOS-DEV/MAELSTROM/tree/master/usecases/francois/syntheticFlowWithWell/case2_multiphaseFlow
2. Change useMass to 0 (as in [case2.txt](https://github.com/GEOS-DEV/GEOS/files/12562306/case2.txt))
3. Run and observe:
```
Time: 2.27e+05 s, dt: 122229.06002827568 s, Cycle: 11
    Attempt:  0, ConfigurationIter:  0, NewtonIter:  0
    ( Rflow ) = ( 3.48e-01 ) ;     ( Rwell ) = ( 1.67e-16 ) ;     ( R ) = ( 3.48e-01 ) ; 
{ 4, 5 }
		Linear Solver | NotConverged | Iterations: 200 | Final Rel Res: 0.983071 | Make Restrictor Time: 0 | Compute Auu Time: 0 | SC Filter Time: 0 | Setup Time: 0.0676049 s | Solve Time: 2.4775 s
    Attempt:  0, ConfigurationIter:  0, NewtonIter:  1
    ( Rflow ) = ( 3.45e-01 ) ;     ( Rwell ) = ( 1.12e-06 ) ;     ( R ) = ( 3.45e-01 ) ; 
    Last LinSolve(iter,res) = ( 200, 9.83e-01 ) ; 
{ 4, 5 }
		Linear Solver | NotConverged | Iterations: 200 | Final Rel Res: 0.00180383 | Make Restrictor Time: 0 | Compute Auu Time: 0 | SC Filter Time: 0 | Setup Time: 0.0702834 s | Solve Time: 3.21096 s
    Attempt:  0, ConfigurationIter:  0, NewtonIter:  2
    ( Rflow ) = ( 4.59e-01 ) ;     ( Rwell ) = ( 2.09e-06 ) ;     ( R ) = ( 4.59e-01 ) ; 
    Last LinSolve(iter,res) = ( 200, 1.80e-03 ) ; 
        Line search @ 0.384:          ( Rflow ) = ( 2.10e-01 ) ;     ( Rwell ) = ( 1.14e-06 ) ; 
{ 4, 5 }
		Linear Solver | Success | Iterations: 182 | Final Rel Res: 9.94522e-09 | Make Restrictor Time: 0 | Compute Auu Time: 0 | SC Filter Time: 0 | Setup Time: 0.0686497 s | Solve Time: 2.0602 s
    Attempt:  0, ConfigurationIter:  0, NewtonIter:  3
    ( Rflow ) = ( 1.77e-01 ) ;     ( Rwell ) = ( 5.18e-07 ) ;     ( R ) = ( 1.77e-01 ) ; 
    Last LinSolve(iter,res) = ( 182, 9.95e-09 ) ; 
{ 4, 5 }
		Linear Solver | Success | Iterations: 177 | Final Rel Res: 8.29353e-09 | Make Restrictor Time: 0 | Compute Auu Time: 0 | SC Filter Time: 0 | Setup Time: 0.0827306 s | Solve Time: 2.00843 s
    Attempt:  0, ConfigurationIter:  0, NewtonIter:  4
    ( Rflow ) = ( 1.13e-02 ) ;     ( Rwell ) = ( 5.05e-07 ) ;     ( R ) = ( 1.13e-02 ) ; 
    Last LinSolve(iter,res) = ( 177, 8.29e-09 ) ; 
{ 4, 5 }
		Linear Solver | NotConverged | Iterations: 200 | Final Rel Res: 0.128202 | Make Restrictor Time: 0 | Compute Auu Time: 0 | SC Filter Time: 0 | Setup Time: 0.0692166 s | Solve Time: 2.41266 s
    Attempt:  0, ConfigurationIter:  0, NewtonIter:  5
    ( Rflow ) = ( 1.18e-02 ) ;     ( Rwell ) = ( 1.34e-07 ) ;     ( R ) = ( 1.18e-02 ) ; 
    Last LinSolve(iter,res) = ( 200, 1.28e-01 ) ; 
```

Runs ok with useMass=1 (not default)

### PR DESCRIPTION
**Pull request by paveltomin**
Fix small bug in black oil computations
One test case requires rebaseline, rebase PR here https://github.com/GEOS-DEV/integratedTests/pull/84

### CODE REVIEW

File: src/coreComponents/constitutive/fluid/multifluid/blackOil/BlackOilFluid.hpp [hunk 1]
```diff
@@ -529,8 +529,8 @@ BlackOilFluid::KernelWrapper::
     phaseFraction.value[ipWater] = zw;
 
     // oil
-    phaseCompFraction.value[ipOil][icOil] = zo;
-    phaseCompFraction.value[ipOil][icGas] = zg;
+    phaseCompFraction.value[ipOil][icOil] = zo / ( zo + zg );
+    phaseCompFraction.value[ipOil][icGas] = zg / ( zo + zg );
```
Comment (dkachuma) [inline src/coreComponents/constitutive/fluid/multifluid/blackOil/BlackOilFluid.hpp]: I would have written this as for example `zo / (1 - zw)` which should have no impact here but would have an impact on the derivatives. Have you looked at the Jacobian in this alternative formulation. I find these composition derivatives a bit confusing when honouring that they sum to 1.

**Review by dkachuma — APPROVED** [review]

File: src/coreComponents/constitutive/fluid/multifluid/blackOil/BlackOilFluid.hpp (hunk 1 above)
Comment (paveltomin) [reply src/coreComponents/constitutive/fluid/multifluid/blackOil/BlackOilFluid.hpp]: just checked - Jacobian is the same, number of linear iterations is the same, I will update with your version
