### PR TITLE
A few solver messages rework

### LINKED ISSUE #2775: Aquifer flux unit in the log at each timestep.
**Describe the bug**
In the following log line, the flux units are not very clear, and might be wrong.
`FlowSolverBase compositionalMultiphaseFlow (SimuDeck_aquifer_pression_meme.xml, l.28): at time 100s, the <Aquifer> boundary condition 'aquifer1' produces a flux of -0.6181975187076816 kg (or moles if useMass=0).`
It may be a volume unit that needs to be determined.
The message appears for each Aquifer at each timestep, if `logLevel >= 1`.

**Expected behavior**
A clearer unit expression of the flux.

**Side note**
We are currently investigating this. The message could be edited in one of my current PRs.

### PR DESCRIPTION
**Pull request by MelReyCG**
This PR aims to rework some messages by:

- using meaningful class names in log lines & errors instead of abstract class names (using the final class catalog name, as it is done in other places).

- fixing the unit in use in the following log line:
`FlowSolverBase compositionalMultiphaseFlow (aquifer.xml, l.28): at time 100s, the <Aquifer> boundary condition 'aquifer1' produces a flux of -0.6181975187076816 kg (or moles if useMass=0).`
Our investigations showed that the output value is in `m³`. 
The proposed new formulation is:
`Aquifer aquifer1 (aquifer.xml, l.226): at time 100s, the boundary condition produces a flux of -0.6181975187076816 m3.`

- remove some direct `fmt::format` reference in favor of `GEOS_FMT`.

### CODE REVIEW

File: src/coreComponents/physicsSolvers/SolverBase.hpp [hunk 1]
```diff
@@ -53,6 +53,11 @@ class SolverBase : public ExecutableGroup
 
   static string catalogName() { return "SolverBase"; }
```
Comment (paveltomin) [inline src/coreComponents/physicsSolvers/SolverBase.hpp:54]: @rrsettgast should we remove all those `base` catalogNames?

File: src/coreComponents/physicsSolvers/contact/LagrangianContactSolver.hpp [hunk 2]
```diff
@@ -44,6 +44,10 @@ class LagrangianContactSolver : public ContactSolverBase
   {
     return "LagrangianContact";
   }
+  /**
+   * @copydoc SolverBase::getCatalogName()
+   */
+  string getCatalogName() const override { return catalogName(); }
```
Comment (paveltomin) [inline src/coreComponents/physicsSolvers/contact/LagrangianContactSolver.hpp:50]: would it be possible to avoid redefining that function for every solver?

File: src/coreComponents/physicsSolvers/SolverBase.hpp (hunk 1 above)
Comment (rrsettgast) [reply src/coreComponents/physicsSolvers/SolverBase.hpp:54]: yes...but we can do that in its own PR. We can also do some of what we talked about yesterday.

File: src/coreComponents/physicsSolvers/contact/LagrangianContactSolver.hpp (hunk 2 above)
Comment (rrsettgast) [reply src/coreComponents/physicsSolvers/contact/LagrangianContactSolver.hpp:50]: No. It is a virtual function, so it will give the right name when you ask for the name through a base pointer....unless there is a way to have a derived class override a virtual function without defining the override.

File: src/coreComponents/physicsSolvers/fluidFlow/FlowSolverBase.cpp [hunk 3]
```diff
@@ -707,9 +707,9 @@ void FlowSolverBase::saveAquiferConvergedState( real64 const & time,
 
     if( bc.getLogLevel() >= 1 )
     {
-      GEOS_LOG_RANK_0( GEOS_FMT( string( "FlowSolverBase {}: at time {}s, " )
-                                 + string( "the <{}> boundary condition '{}' produces a flux of {} kg (or moles if useMass=0). " ),
-                                 getDataContext(), time+dt, AquiferBoundaryCondition::catalogName(), bc.getName(), dt * globalSumFluxes[aquiferIndex] ) );
+      GEOS_LOG_RANK_0( GEOS_FMT( "{} {}: at time {}s, the boundary condition produces a flux of {} m3.",
+                                 AquiferBoundaryCondition::catalogName(), bc.getDataContext(),
```
Comment (paveltomin) [inline src/coreComponents/physicsSolvers/fluidFlow/FlowSolverBase.cpp]: I am not a big fan of so detailed output about xml and line here to be honest.
I think it makes total sense for input error messages but not so much value for simulation dynamic data such as aquifer flux here. Just aquifer name is enough imho.

**Review by paveltomin — APPROVED** [review]

File: src/coreComponents/physicsSolvers/fluidFlow/FlowSolverBase.cpp [hunk 4]
```diff
@@ -707,9 +707,9 @@ void FlowSolverBase::saveAquiferConvergedState( real64 const & time,
 
     if( bc.getLogLevel() >= 1 )
     {
-      GEOS_LOG_RANK_0( GEOS_FMT( string( "FlowSolverBase {}: at time {}s, " )
-                                 + string( "the <{}> boundary condition '{}' produces a flux of {} kg (or moles if useMass=0). " ),
-                                 getDataContext(), time+dt, AquiferBoundaryCondition::catalogName(), bc.getName(), dt * globalSumFluxes[aquiferIndex] ) );
+      GEOS_LOG_RANK_0( GEOS_FMT( "{} {}: at time {}s, the boundary condition produces a flux of {} m3.",
```
Comment (dkachuma) [inline src/coreComponents/physicsSolvers/fluidFlow/FlowSolverBase.cpp]: I agree with m3. I would say this is a volume.

File: src/coreComponents/physicsSolvers/solidMechanics/SolidMechanicsLagrangianFEM.cpp [hunk 5]
```diff
@@ -710,17 +710,17 @@ void SolidMechanicsLagrangianFEM::applyDisplacementBCImplicit( real64 const time
 
     char const bcLogMessage[] =
       "\nWarning!"
-      "\n{} `{}`: There is no displacement boundary condition applied to this problem in the {} direction. \n"
+      "\n{} {}: There is no displacement boundary condition applied to this problem in the {} direction. \n"
       "The problem may be ill-posed.\n";
     GEOS_LOG_RANK_0_IF( isDisplacementBCAppliedGlobal[0] == 0, // target set is empty
```
Comment (dkachuma) [inline src/coreComponents/physicsSolvers/solidMechanics/SolidMechanicsLagrangianFEM.cpp]: Can we use `GEOS_WARNING` or some such? After all it is a warning.

**Review by dkachuma — APPROVED** [review]

**Comment by paveltomin** [comment]
@MelReyCG please resolve conflicting files

File: src/coreComponents/physicsSolvers/fluidFlow/FlowSolverBase.cpp (hunk 3 above)
Comment (paveltomin) [reply src/coreComponents/physicsSolvers/fluidFlow/FlowSolverBase.cpp]: I insist on not printing xml file name and line number here

Comment (TotoGaz) [reply src/coreComponents/physicsSolvers/fluidFlow/FlowSolverBase.cpp]: What is the output that @MelReyCG 's PR will produce?

Comment (paveltomin) [reply src/coreComponents/physicsSolvers/fluidFlow/FlowSolverBase.cpp]: the one from PR description above:
`Aquifer aquifer1 (aquifer.xml, l.226): at time 100s, the boundary condition produces a flux of -0.6181975187076816 m3.`

Comment (paveltomin) [reply src/coreComponents/physicsSolvers/fluidFlow/FlowSolverBase.cpp]: and I would appreciate spaces between values and units, forgot about that before, sorry

Comment (TotoGaz) [reply src/coreComponents/physicsSolvers/fluidFlow/FlowSolverBase.cpp]: Hmm, yes it makes sense. If there's nothing that the user should be doing on line `226` to fix the issue (if this even is an issue...), then we could remove the information to reduce the noise.
@paveltomin Are there any other places where you'd like this pattern to be changed?
Also, we're now top of the merge queue. Should we move on nevertheless?
What's your take @jeannepellerin ?

Comment (paveltomin) [reply src/coreComponents/physicsSolvers/fluidFlow/FlowSolverBase.cpp]: Thanks, I think you got my point. For input errors reporting file name and location is very helpful. Doesn't make much sense for solver issues, and even less sense for results reporting.
I can check other places tomorrow, but I am also ok with merging, it's not that big deal.

File: src/coreComponents/physicsSolvers/multiphysics/CompositionalMultiphaseReservoirAndWells.cpp [hunk 6]
```diff
@@ -280,8 +280,8 @@ assembleCouplingTerms( real64 const time_n,
   using COFFSET = compositionalMultiphaseWellKernels::ColOffset;
 
   GEOS_THROW_IF( !Base::m_isWellTransmissibilityComputed,
-                 GEOS_FMT( "{} `{}`: The well transmissibility has not been computed yet",
-                           catalogName(), this->getName() ),
+                 GEOS_FMT( "{} {}: The well transmissibility has not been computed yet",
+                           this->getCatalogName(), this->getDataContext() ),
```
Comment (paveltomin) [inline src/coreComponents/physicsSolvers/multiphysics/CompositionalMultiphaseReservoirAndWells.cpp]: `getDataContext` does not make much sense here since user would not be able to fix this error from the input side
(it's internal consistency check)

File: src/coreComponents/physicsSolvers/multiphysics/MultiphasePoromechanics.cpp [hunk 7]
```diff
@@ -351,22 +352,23 @@ void MultiphasePoromechanics< FLOW_SOLVER >::initializePostInitialConditionsPreS
...
                    InputError );
   }
 
   integer & isFlowThermal = flowSolver()->isThermal();
-  GEOS_LOG_RANK_0_IF( m_isThermal && !isFlowThermal,
-                      GEOS_FMT( "{} {}: The attribute `{}` of the flow solver `{}` is set to 1 since the poromechanics solver is thermal",
-                                catalogName(), this->getName(), FlowSolverBase::viewKeyStruct::isThermalString(), flowSolver()->getName() ) );
+  GEOS_WARNING_IF( m_isThermal && !isFlowThermal,
+                   GEOS_FMT( "{} {}: The attribute `{}` of the flow solver `{}` is set to 1 since the poromechanics solver is thermal",
+                             getCatalogName(), this->getDataContext(), FlowSolverBase::viewKeyStruct::isThermalString(), flowSolver()->getDataContext() ) );
```
Comment (paveltomin) [inline src/coreComponents/physicsSolvers/multiphysics/MultiphasePoromechanics.cpp]: `getDataContext` does not make much sense here

File: src/coreComponents/physicsSolvers/multiphysics/SinglePhasePoromechanics.cpp [hunk 8]
```diff
@@ -252,15 +252,15 @@ void SinglePhasePoromechanics< FLOW_SOLVER >::initializePostInitialConditionsPre
...
+                             getCatalogName(), this->getDataContext(), poromechanicsTargetRegionNames[i], flowSolver()->getDataContext() ),
                    InputError );
   }
 
   integer & isFlowThermal = flowSolver()->isThermal();
   GEOS_LOG_RANK_0_IF( m_isThermal && !isFlowThermal,
                       GEOS_FMT( "{} {}: The attribute `{}` of the flow solver `{}` is set to 1 since the poromechanics solver is thermal",
-                                catalogName(), this->getDataContext().toString(),
-                                FlowSolverBase::viewKeyStruct::isThermalString(), flowSolver()->getName() ) );
+                                getCatalogName(), this->getDataContext(),
```
Comment (paveltomin) [inline src/coreComponents/physicsSolvers/multiphysics/SinglePhasePoromechanics.cpp]: and here

File: src/coreComponents/physicsSolvers/multiphysics/SinglePhaseReservoirAndWells.cpp [hunk 9]
```diff
@@ -249,8 +249,8 @@ assembleCouplingTerms( real64 const time_n,
   using COFFSET = singlePhaseWellKernels::ColOffset;
 
   GEOS_THROW_IF( !Base::m_isWellTransmissibilityComputed,
-                 GEOS_FMT( "{} `{}`: The well transmissibility has not been computed yet",
-                           catalogName(), this->getName() ),
+                 GEOS_FMT( "{} {}: The well transmissibility has not been computed yet",
```
Comment (paveltomin) [inline src/coreComponents/physicsSolvers/multiphysics/SinglePhaseReservoirAndWells.cpp:252]: and here

File: src/coreComponents/physicsSolvers/fluidFlow/FlowSolverBase.cpp (hunk 3 above)
Comment (MelReyCG) [reply src/coreComponents/physicsSolvers/fluidFlow/FlowSolverBase.cpp]: I agree with your point, I replaced this precise call to `getDataContext()` by a `getName()`.
I tried to find other infos message that use `getDataContext()` but didn't find any.

File: src/coreComponents/physicsSolvers/multiphysics/CompositionalMultiphaseReservoirAndWells.cpp (hunk 6 above)
Comment (MelReyCG) [reply src/coreComponents/physicsSolvers/multiphysics/CompositionalMultiphaseReservoirAndWells.cpp]: Ok! (for this and the next ones)

**Comment by MelReyCG** [comment]
I took the last comments into account, is it good to go ?

**Comment by paveltomin** [comment]
> This branch has conflicts that must be resolved

As long as the file conflict is resolved :)
